
spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

jwt:
  secret: "himynameisjaeyunkimhellonicetomeetyouohmygottooshorthahahohohihihuhu"